name: "rps"
version: "1.0"
config-version: 2

profile: "rps"

models:
  rps:
    core:
      +materialized: table
      +schema: core

    staging:
      +materialized: view
      +schema: stg

    marts:
      +materialized: table
      +schema: mart
