name: "rps"
version: "1.0"
config-version: 2

profile: "rps"

models:
  rps:
    core:
      +materialized: table
      +schema: rps_core

    staging:
      +materialized: view
      +schema: rps_stg

    marts:
      +materialized: table
      +schema: rps_mart
