---
version: 2

models:
  # Staging views
  - name: stg_sales
    description: Cleaned sales data from rps_raw.sales_raw.
    columns:
      - name: date_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]
      - name: region_id
        tests: [not_null]

  - name: stg_rebates
    description: Cleaned rebates data from rps_raw.rebates_raw.
    columns:
      - name: date_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]
      - name: region_id
        tests: [not_null]

  - name: stg_promo
    description: Cleaned promo data from rps_raw.promo_raw.
    columns:
      - name: date_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]
      - name: region_id
        tests: [not_null]

  - name: stg_forecast
    description: Cleaned forecast data from rps_raw.forecast_raw.
    columns:
      - name: date_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]
      - name: region_id
        tests: [not_null]

  # Marts
  - name: mart_gtn_waterfall
    columns:
      - name: year
        tests: [not_null]
      - name: month
        tests: [not_null]
      - name: brand
        tests: [not_null]
      - name: canton
        tests: [not_null]
  - name: mart_brand_perf
    columns:
      - name: year
        tests: [not_null]
      - name: month
        tests: [not_null]
      - name: brand
        tests: [not_null]
      - name: canton
        tests: [not_null]
  - name: mart_forecast_accuracy
    columns:
      - name: year
        tests: [not_null]
      - name: month
        tests: [not_null]
      - name: brand
        tests: [not_null]
      - name: canton
        tests: [not_null]
