---
version: 2

models:
  # STAGING
  - name: stg_sales
    columns:
      - name: product_id
        tests: [not_null]
      - name: region_id
        tests: [not_null]
      - name: date_id
        tests:
          - not_null:
              severity: warn

  - name: stg_rebates
    columns:
      - name: product_id
        tests: [not_null]
      - name: region_id
        tests: [not_null]
      - name: date_id
        tests:
          - not_null:
              severity: warn

  - name: stg_promo
    columns:
      - name: product_id
        tests: [not_null]
      - name: region_id
        tests: [not_null]
      - name: date_id
        tests:
          - not_null:
              severity: warn

  - name: stg_forecast
    columns:
      - name: product_id
        tests: [not_null]
      - name: region_id
        tests: [not_null]
      - name: date_id
        tests:
          - not_null:
              severity: warn

  # (MARTS keep your stricter tests, since they should only contain
  #  fully conformant records after joins/filters.)
  - name: mart_gtn_waterfall
    columns:
      - name: year
        tests: [not_null]
      - name: month
        tests: [not_null]
      - name: brand
        tests: [not_null]
      - name: canton
        tests: [not_null]
  - name: mart_brand_perf
    columns:
      - name: year
        tests: [not_null]
      - name: month
        tests: [not_null]
      - name: brand
        tests: [not_null]
      - name: canton
        tests: [not_null]
  - name: mart_forecast_accuracy
    columns:
      - name: year
        tests: [not_null]
      - name: month
        tests: [not_null]
      - name: brand
        tests: [not_null]
      - name: canton
        tests: [not_null]
