repos:
  # Core hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json

  # Python (formatter then linter)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix]

  # SQL (lint and optional fix)
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.2
    hooks:
      - id: sqlfluff-lint
        name: sqlfluff-lint
        args: ["--config=.sqlfluff"]
        additional_dependencies:
          - sqlfluff-templater-dbt==3.4.2
          - dbt-core==1.7.15
          - dbt-postgres==1.7.15
          - "protobuf<5"
      - id: sqlfluff-fix
        name: sqlfluff-fix
        args: ["--config=.sqlfluff"]
        additional_dependencies:
          - sqlfluff-templater-dbt==3.4.2
          - dbt-core==1.7.15
          - dbt-postgres==1.7.15
          - "protobuf<5"

  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint
        name: hadolint
        language: system
        entry: hadolint
        files: ^(Dockerfile|.*/Dockerfile)$

  # YAML lint
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        files: \.ya?ml$

  # Prettier for Markdown/JSON/YAML (requires Node installed)
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.6.2 # any valid tag from this fork works; 3.3.3, 3.4.x, 3.6.x, etc.
    hooks:
      - id: prettier
        files: \.(md|ya?ml|json)$
