version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: rps_postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  generator:
    build: ./generator
    container_name: rps_generator
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      SCALE: ${SCALE:-small}
      TZ: ${TZ}
    command: ["python", "generate.py"]

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:latest
    container_name: rps_dbt
    working_dir: /usr/app
    environment:
      DBT_PROFILES_DIR: /usr/app
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      TZ: ${TZ}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./dbt:/usr/app

  streamlit:
    build: ./streamlit
    container_name: rps_streamlit
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      TZ: ${TZ}
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit:/app

  metabase:
    image: metabase/metabase:latest
    container_name: rps_metabase
    ports:
      - "3000:3000"
    environment:
      TZ: ${TZ}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./metabase-data:/metabase-data

volumes:
  pgdata: